module FindAI
  module Models
    type search_retrieve_params =
      {  } & FindAI::Internal::Type::request_parameters

    class SearchRetrieveParams < FindAI::BaseModel
      extend FindAI::Internal::Type::RequestParameters::Converter
      include FindAI::Internal::Type::RequestParameters

      def initialize: (?request_options: FindAI::request_opts) -> void

      def to_hash: -> FindAI::Models::search_retrieve_params
    end
  end
end
