module FindAI
  module Models
    type search_retrieve_params =
      {  } & FindAI::Internal::Type::request_parameters

    class SearchRetrieveParams < FindAI::Internal::Type::BaseModel
      extend FindAI::Internal::Type::RequestParameters::Converter
      include FindAI::Internal::Type::RequestParameters

      def initialize: (?request_options: FindAI::request_opts) -> void
    end
  end
end
