module FindAI
  class Unknown = FindAI::Internal::Type::Unknown

  class BooleanModel = FindAI::Internal::Type::BooleanModel

  module Enum = FindAI::Internal::Type::Enum

  module Union = FindAI::Internal::Type::Union

  class ArrayOf = FindAI::Internal::Type::ArrayOf

  class HashOf = FindAI::Internal::Type::HashOf

  class BaseModel = FindAI::Internal::Type::BaseModel

  type request_parameters = FindAI::Internal::Type::request_parameters

  module RequestParameters = FindAI::Internal::Type::RequestParameters
end
