module FindAI
  module Resources
    class Searches
      def create: (
        ?max_matches: Float,
        ?query: String,
        ?result_mode: FindAI::Models::SearchCreateParams::result_mode,
        ?scope: FindAI::Models::SearchCreateParams::scope,
        ?request_options: FindAI::request_opts
      ) -> FindAI::Models::SearchCreateResponse

      def retrieve: (
        String id,
        ?request_options: FindAI::request_opts
      ) -> FindAI::Models::search_retrieve_response

      def initialize: (client: FindAI::Client) -> void
    end
  end
end
